In [27]:
import numpy as np
import pandas as pd

In [28]:
# 개선점
###### 구글 코랩 세션 유지 javascript 코드 추가 (1분마다 자동 재연결) https://naenjun.tistory.com/18
###### 코랩에 mysql 연결

!pip install PyMySQL

import pymysql

In [140]:
from requests import get
# pip install requests

ip = get("https://api.ipify.org").text
print("My public IP address : ", ip)

juso_db = pymysql.connect(
    user='kym', 
    passwd='kim', 
    host='13.209.100.19', 
    db='test', 
    charset='utf8'
)

My public IP address :  211.41.239.73


In [141]:
# SQL문 실행
# Connection 으로부터 Cursor 생성
curs = juso_db.cursor(pymysql.cursors.DictCursor)

sql = "SELECT elec.electric, prod.id, prod.name, prod.location, DATE_FORMAT(TRUNCATE(elec.datetime, -2), '%Y-%m-%d %H:%i:%s') datetime, env.temp, env.humid FROM elec_stat elec INNER JOIN env env ON DATE_FORMAT(TRUNCATE(elec.datetime, -2), '%Y-%m-%d %H:%i:%s') = DATE_FORMAT(TRUNCATE(env.datetime, -2), '%Y-%m-%d %H:%i:%s') INNER JOIN product prod ON elec.prod_id = prod.id"
curs.execute(sql)
 
# 데이타 Fetch
rows = curs.fetchall()
print(rows)     # 전체 rows

[{'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 16:55:00', 'temp': 24, 'humid': 37}, {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:05:00', 'temp': 24, 'humid': 37}, {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:15:00', 'temp': 24, 'humid': 37}, {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:25:00', 'temp': 24, 'humid': 37}, {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:35:00', 'temp': 24, 'humid': 38}, {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:45:00', 'temp': 24, 'humid': 38}, {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:55:00', 'temp': 24, 'humid': 38}, {'electric': 0.156916, 'id': 111, 'name'

In [40]:
r_data = np.array(rows)
r_data

array([{'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 16:55:00', 'temp': 24, 'humid': 37},
       {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:05:00', 'temp': 24, 'humid': 37},
       {'electric': 0.156916, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-01-22 17:15:00', 'temp': 24, 'humid': 37},
       ...,
       {'electric': 0.052305, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-02-03 15:25:00', 'temp': 24, 'humid': 17},
       {'electric': 0.052305, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-02-03 15:30:00', 'temp': 24, 'humid': 17},
       {'electric': 0.183068, 'id': 111, 'name': 'Monitor', 'location': 'DH_HOME', 'datetime': '2021-02-03 16:15:00', 'temp': 19, 'humid': 13}],
      dtype=object)

In [109]:
df = pd.DataFrame(rows)
df

electric   id     name location             datetime  temp  humid
0     0.156916  111  Monitor  DH_HOME  2021-01-22 16:55:00    24     37
1     0.156916  111  Monitor  DH_HOME  2021-01-22 17:05:00    24     37
2     0.156916  111  Monitor  DH_HOME  2021-01-22 17:15:00    24     37
3     0.156916  111  Monitor  DH_HOME  2021-01-22 17:25:00    24     37
4     0.156916  111  Monitor  DH_HOME  2021-01-22 17:35:00    24     38
...        ...  ...      ...      ...                  ...   ...    ...
2550  0.052305  111  Monitor  DH_HOME  2021-02-03 14:35:00    24     14
2551  0.052305  111  Monitor  DH_HOME  2021-02-03 14:40:00    24     15
2552  0.052305  111  Monitor  DH_HOME  2021-02-03 15:25:00    24     17
2553  0.052305  111  Monitor  DH_HOME  2021-02-03 15:30:00    24     17
2554  0.183068  111  Monitor  DH_HOME  2021-02-03 16:15:00    19     13

[2555 rows x 7 columns]

In [110]:
dataTestY = df.values[:,0]
dataTestY01 = dataTestY.astype(float)
dataTestY01

array([0.156916, 0.156916, 0.156916, ..., 0.052305, 0.052305, 0.183068])

In [111]:
#userPeakValue = 0.1
#testY = dataTestY01//userPeakValue
#testY[:30]

In [112]:
dataTestX= df[['id', 'temp', 'humid']]
testX = dataTestX.values
dataTestX01 = testX.astype(float)
testX[:15]

array([[111,  24,  37],
       [111,  24,  37],
       [111,  24,  37],
       [111,  24,  37],
       [111,  24,  38],
       [111,  24,  38],
       [111,  24,  38],
       [111,  24,  37],
       [111,  24,  37],
       [111,  24,  38],
       [111,  24,  37],
       [111,  24,  37],
       [111,  24,  37],
       [111,  24,  37],
       [111,  24,  37]], dtype=int64)

In [113]:
from sklearn.ensemble import RandomForestClassifier

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
def 모델평가(model, X, y, **설정):
    X_train, X_test, y_train, y_test = train_test_split(X, y, **설정)
    model.fit(X_train, y_train)
    훈련점수 = model.score(X_train, y_train)
    시험점수 = model.score(X_test, y_test)
    return 훈련점수, 시험점수

In [120]:
energe_forest = RandomForestClassifier(n_estimators=100)
모델평가(energe_forest, testX, testY)

(0.8225469728601252, 0.7996870109546166)

## ------------------------------------ 전력 분포 확인용 ------------------------------------

In [143]:
from requests import get
# pip install requests

ip = get("https://api.ipify.org").text
print("My public IP address : ", ip)

juso_db = pymysql.connect(
    user='kym', 
    passwd='kim', 
    host='13.209.100.19', 
    db='test', 
    charset='utf8'
)

My public IP address :  211.41.239.73


In [146]:
# SQL문 실행
# Connection 으로부터 Cursor 생성
curs = juso_db.cursor(pymysql.cursors.DictCursor)

sql = "SELECT electric FROM elec_stat"
curs.execute(sql)
 
# 데이타 Fetch
rows = curs.fetchall()
print(rows)     # 전체 rows

[{'electric': 0.078458}, {'electric': 26.7803}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.156916}, {'electric': 0.052305}, {'electric': 0.052305}, {'electric': 0.052305}, {'electric': 0.052305}, {'electric': 0.052305}, {'electric': 0.052305}, {'electric': 0.156916}, {'electric': 0.1

In [149]:
df = pd.DataFrame(rows)
df['electric'].unique()# 10개?

array([7.84580e-02, 2.67803e+01, 1.56916e-01, 5.23050e-02, 1.30763e-01,
       2.61530e-02, 2.87679e-01, 2.61526e-01, 2.09221e-01, 1.83068e-01])

In [121]:
# Connection 닫기
juso_db.close()